name: CUBIDES
favicon: null
layout_spectrum: 0.5770609
typography_spectrum: 0.3880256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4507824
  lightness: 0.4910394
  saturation: 0.5322581
  rhythmicContrast: 0.5949821
purpose: []
