name: CUBIDES
favicon: null
layout_spectrum: 0.49204
typography_spectrum: 0.6233
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252326'
    - '#c3382f'
    - '#c4b4b7'
    - '#f1a360'
    - '#67433d'
  brandStrength: 0.4507824
  lightness: 0.4910394
  saturation: 0.5322581
  rhythmicContrast: 0.5949821
purpose: []
