name: CUBIDES
favicon: null
layout_spectrum: 0.5770609
typography_spectrum: 0.3880256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252326'
    - '#c3382f'
    - '#c4b4b7'
    - '#f1a360'
    - '#67433d'
  brandStrength: 0.4507824
  lightness: 0.4910394
  saturation: 0.5322581
  rhythmicContrast: 0.5949821
purpose: []
